name: Build and Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build-mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # Restore .env.production.demo from a GitHub secret
      - name: Restore .env.production.demo
        run: |
          echo "${{ secrets.DEMO_ENV_FILE }}" > .env.production.demo

      - run: npm ci
      - run: npm run build:demo
        env:
          CSC_IDENTITY_AUTO_DISCOVERY: false
          CSC_NAME: "Developer ID Application: Marika Basagoitia (R9ZPUC7AGS)"
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_APP_SPECIFIC_PASSWORD: ${{ secrets.APPLE_APP_SPECIFIC_PASSWORD }}
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
      - uses: actions/upload-artifact@v4
        with:
          name: mac-build
          path: dist/demo/*

  build-win:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # Restore .env.production.demo from a GitHub secret.
      - name: Restore .env.production.demo
        run: |
          echo "${{ secrets.DEMO_ENV_FILE }}" > .env.production.demo

      - run: npm ci
      - run: npm run build:demo
        env:
          WIN_CSC_LINK: ${{ secrets.WIN_CSC_LINK }}
          WIN_CSC_KEY_PASSWORD: ${{ secrets.WIN_CSC_KEY_PASSWORD }}
      - uses: actions/upload-artifact@v4
        with:
          name: win-build
          path: dist/demo/*

  release:
    runs-on: ubuntu-latest
    needs: [build-mac, build-win]
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: mac-build
          path: dist-mac
      - uses: actions/download-artifact@v4
        with:
          name: win-build
          path: dist-win
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist-mac/*
            dist-win/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
