build-mac:
  runs-on: macos-latest
  steps:
    - uses: actions/checkout@v4
    - name: Set up Node
      uses: actions/setup-node@v4
      with:
        node-version: 20

    # Restore .env.production.demo from a GitHub secret
    - name: Restore .env.production.demo
      run: |
        echo "${{ secrets.DEMO_ENV_FILE }}" > .env.production.demo

    # Generate config.demo.json dynamically
    - name: Generate config.demo.json
      run: |
        cat <<EOF > config.demo.json
        {
          "APP_MODE": "demo",
          "APP_DEV_MODE": false,
          "HTTPS": false,
          "HOST": "localhost",
          "PORT": 3000,
          "WDS_SOCKET_PORT": 3000,
          "API_BASE": "${{ secrets.DEMO_API_BASE }}",
          "API_PORT": 5000,
          "SQLITE_FILE": "${{ secrets.DEMO_SQLITE_FILE }}"
        }
        EOF

    - run: npm ci

    # Build with electron-builder and sign
    - run: npm run build:demo
      env:
        CSC_LINK: ${{ secrets.MAC_CSC_LINK }}   # directly use base64 secret
        CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
        CSC_IDENTITY_AUTO_DISCOVERY: false
        APPLE_ID: ${{ secrets.APPLE_ID }}
        APPLE_APP_SPECIFIC_PASSWORD: ${{ secrets.APPLE_APP_SPECIFIC_PASSWORD }}
        APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}

    - uses: actions/upload-artifact@v4
      with:
        name: mac-build
        path: dist/demo/*
